library(datasets)
electric_data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, colClasses = "character")
electric_data$Date <- as.Date(electric_data$Date, "%d/%m/%Y")
subset_data <- subset(electric_data, Date == "2007-02-01" | Date == "2007-02-02")
datetime <- paste(subset_data$Date, subset_data$Time)
datetime <- strptime(datetime, "%Y-%m-%d %H:%M:%S")
subset_data[,3] <- as.numeric(subset_data[,3])
plot(datetime, subset_data$Global_active_power, type = "l", xlab ="", ylab = "Global Active Power (Kilowatts)")
dev.copy(png,"plot2.png", width = 480, height = 480, units = "px", bg = "white")
dev.off()